archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.revision={{.Version}}-{{.Commit}}-{{.Date}} -s -w
dockers:
  - goarch: amd64
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/a1fred/alertmanager-telegram:latest"
      - "ghcr.io/a1fred/alertmanager-telegram:{{.Version}}"
      - "ghcr.io/a1fred/alertmanager-telegram:{{ .Major }}"
      - "ghcr.io/a1fred/alertmanager-telegram:{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - --platform=linux/amd64
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goarch: arm64
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/a1fred/alertmanager-telegram:latest-arm64"
      - "ghcr.io/a1fred/alertmanager-telegram{{.Version}}-arm64"
      - "ghcr.io/a1fred/alertmanager-telegram:{{ .Major }}-arm64"
      - "ghcr.io/a1fred/alertmanager-telegram:{{ .Major }}.{{ .Minor }}-arm64"
    build_flag_templates:
      - --platform=linux/arm64/v8
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
