BRANCH=$(subst /,-,$(B))
GITREV=$(shell git describe --abbrev=7 --always --tags)
REV=$(GITREV)-$(BRANCH)-$(shell date +%Y%m%d-%H:%M:%S)
DOCFILE=CLI.md
TARGET=alertmanager-telegram

.PHONY: all
all: lint test doc build

.PHONY: clean
clean:
	rm -rf build cover.out alertmanager

lint:
	golangci-lint run --timeout=2m0s

.PHONY: test
test: lint
	go test -coverprofile cover.out ./...
	go tool cover -func cover.out

.PHONY: build
build:
	CGO_ENABLED=0 go build -ldflags "-X main.revision=$(REV) -s -w" -o build/$(TARGET)

.PHONY: doc
doc:
	echo "[//]: <> (DO NOT TOUCH! THIS FILE IS GENERATED BY make doc)"  > $(DOCFILE)
	echo "# $(TARGET) cli" >> $(DOCFILE)
	echo "\`\`\`shell" >> $(DOCFILE)
	echo "$$ $(TARGET) --help" >> $(DOCFILE)
	sh -c "go run main.go --help || true" >> $(DOCFILE) 2>&1
	echo "\`\`\`" >> $(DOCFILE)

	echo "## Daemon" >> $(DOCFILE)
	echo "\`\`\`shell" >> $(DOCFILE)
	echo "$$ $(TARGET) daemon --help" >> $(DOCFILE)
	sh -c "go run main.go daemon --help || true" >> $(DOCFILE) 2>&1
	echo "\`\`\`" >> $(DOCFILE)


alertmanager:
	wget https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.darwin-amd64.tar.gz
	mkdir alertmanager
	tar -xzvf alertmanager-0.23.0.darwin-amd64.tar.gz -C alertmanager/ --strip-components=1
	rm alertmanager-0.23.0.darwin-amd64.tar.gz
alertmanager_run:
	alertmanager/alertmanager --config.file=alertmanager.yml --storage.path=alertmanager/data

.PHONY: alert
alert:
	sh test-alert.sh
